variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: docker:24.0.5
  DOCKER_SERVICE: docker:24.0.5-dind

stages:
  - build

# Template to avoid repeating login and service setup
.docker_setup: &docker_setup
  image: $DOCKER_IMAGE
  services:
    - $DOCKER_SERVICE
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # 1. Pull the existing image to use its layers as cache
    - docker pull $IMAGE_TAG || true
    # 2. Build using the pulled image as a cache source
    - >
      docker build 
      --pull 
      --cache-from $IMAGE_TAG 
      --build-arg APP_MODE=$APP_MODE 
      -t $IMAGE_TAG .
    # 3. Push the new version
    - docker push $IMAGE_TAG

prod:
  <<: *docker_setup
  stage: build
  variables:
    IMAGE_TAG: '$CI_REGISTRY_IMAGE:latest'
    APP_MODE: 'prod'
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

acc:
  <<: *docker_setup
  stage: build
  variables:
    IMAGE_TAG: '$CI_REGISTRY_IMAGE:acc'
    APP_MODE: 'acc'
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
