---
- name: Update apt cache and upgrade system
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install basic dependencies
  apt:
    name:
      - curl
      - git
      - gnupg
      - python3-psycopg2
    state: present