---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL is started
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create database user
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: CREATEDB

- name: Create application database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_user }}"